# Generated by Django 3.2.3 on 2021-05-27 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Entity_Info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods_Brench_Storage',
            fields=[
                ('goods_storage_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('goods_storage_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Goods_Info',
            fields=[
                ('SKU', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('branch_sale_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Company_Purchase',
            fields=[
                ('goods_purchase_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('goods_purchase_time', models.DateTimeField()),
                ('SKU', models.IntegerField()),
                ('goods_supply_time', models.DateTimeField(null=True)),
                ('goods_purchase_num', models.IntegerField()),
                ('goods_purchase_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Purchase_user_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Entity_Info.user_info')),
                ('purchase_storage_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Entity_Info.storage_info')),
            ],
        ),
        migrations.CreateModel(
            name='Company_Branch_Delivery',
            fields=[
                ('goods_delivery_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('goods_delivery_send_time', models.DateTimeField()),
                ('branch_sale_receive_time', models.DateTimeField(null=True)),
                ('goods_num', models.IntegerField()),
                ('delivery_branch_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Entity_Info.branch_info')),
                ('delivery_goods_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Entity_Info.goods_info')),
                ('delivery_storage_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Entity_Info.storage_info')),
                ('goods_delivery_staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Entity_Info.user_info')),
            ],
        ),
        migrations.CreateModel(
            name='Branch_Client_Sale',
            fields=[
                ('branch_sale_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('branch_sale_num', models.IntegerField()),
                ('branch_sale_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('branch_sale_time', models.DateTimeField()),
                ('sale_branch_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Entity_Info.branch_info')),
                ('sale_goods_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Entity_Info.goods_info')),
            ],
        ),
    ]
