# Generated by Django 3.2.3 on 2021-05-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relation_Info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch_client_sale',
            name='branch_sale_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='supplier_company_purchase',
            name='goods_purchase_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
