# Generated by Django 3.2.3 on 2021-05-28 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Relation_Info', '0003_auto_20210527_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_branch_delivery',
            old_name='goods_delivery_staff',
            new_name='goods_delivery_staff_id',
        ),
    ]
