# Generated by Django 3.2.3 on 2021-05-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Relation_Info', '0004_rename_goods_delivery_staff_company_branch_delivery_goods_delivery_staff_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_branch_delivery',
            old_name='branch_sale_receive_time',
            new_name='goods_delivery_receive_time',
        ),
    ]
