# Generated by Django 3.2.3 on 2021-05-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relation_Info', '0005_rename_branch_sale_receive_time_company_branch_delivery_goods_delivery_receive_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch_client_sale',
            name='branch_sale_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='branch_client_sale',
            name='branch_sale_num',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='company_branch_delivery',
            name='goods_delivery_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='company_branch_delivery',
            name='goods_num',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='goods_brench_storage',
            name='goods_storage_id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='goods_brench_storage',
            name='goods_storage_num',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='supplier_company_purchase',
            name='SKU',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='supplier_company_purchase',
            name='goods_purchase_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier_company_purchase',
            name='goods_purchase_num',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='supplier_goods_info',
            name='SKU',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
