# Generated by Django 3.2.3 on 2021-06-04 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Relation_Info', '0006_auto_20210528_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier_goods_info',
            old_name='branch_sale_price',
            new_name='order_price',
        ),
    ]
