# Generated by Django 3.2.3 on 2021-05-27 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch_Info',
            fields=[
                ('branch_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('branch_district', models.CharField(max_length=5)),
                ('branch_address', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Goods_Info',
            fields=[
                ('goods_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('goods_name', models.CharField(max_length=10)),
                ('goods_category', models.CharField(max_length=10)),
                ('goods_unit', models.CharField(max_length=4)),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Storage_Info',
            fields=[
                ('storage_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('storage_address', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Info',
            fields=[
                ('supplier_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('supplier_name', models.CharField(max_length=10)),
                ('supplier_mail', models.CharField(max_length=20)),
                ('supplier_tel', models.CharField(max_length=11)),
                ('supplier_address', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('user_account', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('user_psw', models.CharField(max_length=8)),
                ('user_name', models.CharField(max_length=8)),
                ('user_tel', models.CharField(max_length=11)),
                ('user_dep', models.CharField(max_length=5)),
                ('user_branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Entity_Info.branch_info')),
            ],
        ),
    ]
