# Generated by Django 3.2.3 on 2021-05-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity_Info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_info',
            name='goods_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='goods_info',
            name='goods_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_account',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
