# Generated by Django 3.2.3 on 2021-05-27 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entity_Info', '0002_auto_20210527_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Entity_Info.branch_info'),
        ),
    ]
