# Generated by Django 3.2.3 on 2021-05-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity_Info', '0003_alter_user_info_user_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_info',
            name='goods_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='supplier_info',
            name='supplier_name',
            field=models.CharField(max_length=15),
        ),
    ]
