# Generated by Django 3.2.3 on 2021-05-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity_Info', '0004_auto_20210527_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch_info',
            name='branch_id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='storage_info',
            name='storage_id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier_info',
            name='supplier_id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_account',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
